//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constitution_Championnat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constitution_Championnat()
        {
            this.Constitution_Equipes = new HashSet<Constitution_Equipes>();
            this.Matchs = new HashSet<Matchs>();
            this.Matchs1 = new HashSet<Matchs>();
        }
    
        public int CoChmp_ID { get; set; }
        public int CoChmp_Champ_ID { get; set; }
        public int CoChmp_Eqp_ID { get; set; }
        public short CoChmp_Points { get; set; }
    
        public virtual Championnats Championnats { get; set; }
        public virtual Equipes Equipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constitution_Equipes> Constitution_Equipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matchs> Matchs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matchs> Matchs1 { get; set; }
    }
}
