//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constitution_Equipes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constitution_Equipes()
        {
            this.Inscription_Matchs = new HashSet<Inscription_Matchs>();
        }
    
        public int CEqp_ID { get; set; }
        public int CEqp_CoChmp_ID { get; set; }
        public int CEqp_Ssn_ID { get; set; }
        public int CEqp_Jr_ID { get; set; }
    
        public virtual Constitution_Championnat Constitution_Championnat { get; set; }
        public virtual Joueurs Joueurs { get; set; }
        public virtual Saisons Saisons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscription_Matchs> Inscription_Matchs { get; set; }
    }
}
