//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matchs()
        {
            this.Events = new HashSet<Events>();
            this.Inscription_Matchs = new HashSet<Inscription_Matchs>();
            this.Suspensions = new HashSet<Suspensions>();
        }
    
        public int Mch_ID { get; set; }
        public int Mch_Eqp_Dom_ID { get; set; }
        public int Mch_Eqp_Visit_ID { get; set; }
        public int Mch_Ssn_ID { get; set; }
        public Nullable<System.DateTime> Mch_Date { get; set; }
        public Nullable<int> Mch_Res_ID_Dom { get; set; }
        public Nullable<int> Mch_Res_ID_Visit { get; set; }
        public System.DateTime Mch_LastUpdate { get; set; }
    
        public virtual Constitution_Championnat Constitution_Championnat { get; set; }
        public virtual Constitution_Championnat Constitution_Championnat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscription_Matchs> Inscription_Matchs { get; set; }
        public virtual Types_Resultats Types_Resultats { get; set; }
        public virtual Types_Resultats Types_Resultats1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suspensions> Suspensions { get; set; }
        public virtual Saisons Saisons { get; set; }
    }
}
