//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suspensions
    {
        public int Susp_ID { get; set; }
        public Nullable<int> Susp_Mch_ID { get; set; }
        public int Susp_Evnt_ID { get; set; }
        public bool Susp_Executed { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Matchs Matchs { get; set; }
    }
}
